// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guwsxccsdhzrtuywrubv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1d3N4Y2NzZGh6cnR1eXdydWJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjIyNzksImV4cCI6MjA3MDQ5ODI3OX0.yomcNr9ewxb5-SRwHO8453fkpll0YNonDiLQ1gDi5Pk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});